version: '3'
services:

  node-ks-service:
    container_name: node-ks-service
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run dev'
    restart: always
    env_file:
      - .env
    ports:
      - '3222:3222'
      - '9229:9229'
    volumes:
      - ./:/app
      - '/app/node_modules'
    depends_on:
      - node-ks-mongo
      - node-ks-mysql

  node-ks-mongo:
    image: 'mongo:4.0'
    container_name: node-ks-mongo
    ports:
      - '5300:27017'
    volumes:
      - './.data/mongo:/data/db'
      - './.data/mongoconfigdb:/data/configdb'

  node-ks-mysql:
    platform: linux/amd64
    image: 'mysql:5.7.33'
    container_name: node-ks-mysql
    ports:
      - '5302:3306'
    env_file:
      - .env
